Created Rootblock
hacker-h/MyFS pull request #19
Opened 2018-10-12 08:09 UTC by jufabeck2202

Implemented rootblock class,
Created methods to create rootblock,
create inode 
and get Inode

separate tests in test-rootblock

2018-10-12 08:11 UTC, jufabeck2202 commented
rootblock gets overwritten by the class i wrote

2018-10-14 20:46 UTC, hacker-h commented on src/rootblock.cpp
> +        char fileName[FILENAME_MAX] = "empty";
FILENAME_MAX sollte stattdessen NAME_LENGTH sein, um die Vorgabe zu erfüllen

2018-10-14 21:01 UTC, hacker-h requested changes

2018-10-14 21:01 UTC, hacker-h commented on src/rootblock.cpp
> +        createInode(bd,I_MAP_FIRST_BLOCK+i, fileName,0,0,0,0,0,0,0,0);
Die Nullen sollten in eine Konstante ausgelagert werden z.B. EMPTY_INODE_ATTRIBUTE, die einen eindeutigen Wert z.B. 1023 hat, um Verwechslungen zu vermeiden

2018-10-14 21:01 UTC, hacker-h commented on includes/rootblock.h
> +        void create(BlockDevice*bd);
create sollte in init umbenannt werden, da diese Funktion nur ein einziges Mal aufgerufen wird

2018-10-14 21:01 UTC, hacker-h commented on unittests/test-rootblock.cpp
> +        //read inode struct from block 10
Kommentar passt nicht zum Code und sollte angepasst/generalisiert werden, um nicht von einzelnen Zahlen abhängig zu sein

2018-10-14 21:01 UTC, hacker-h commented on unittests/test-rootblock.cpp
> +        rootb->createInode(bd,index,fileName,1,100,100,100,100,100,100,100);
sollte mit "realistischen" Werten getestet werden

2018-10-14 21:01 UTC, hacker-h commented on unittests/test-rootblock.cpp
> +        lastInode = rootb->getInode(bd,I_MAP_FIRST_BLOCK+NUM_DIR_ENTRIES);
statt I_MAP_FIRST_BLOCK+NUM_DIR_ENTRIES bietet sich hier I_MAP_LAST_BLOCK an

2018-10-14 21:01 UTC, hacker-h commented on src/rootblock.cpp
> +        char fileName[FILENAME_MAX] = "empty";
"empty" sollte in eine sprechende Konstante ausgelagert werden

2018-10-14 21:01 UTC, hacker-h commented on unittests/test-rootblock.cpp
> +    SECTION("write / read To inode") {
sollte umbenannt werden z.B. in "update inode + read/write to block device"

2018-10-14 21:01 UTC, hacker-h commented on unittests/test-rootblock.cpp
> +TEST_CASE( "Test Rootblock", "[RootbLock]" ) {
RootbLock  =>  Rootblock

2018-10-15 10:55 UTC, jufabeck2202 commented on unittests/test-rootblock.cpp
> +        lastInode = rootb->getInode(bd,I_MAP_FIRST_BLOCK+NUM_DIR_ENTRIES);
Ja aber die konstanten sind falsch. Wenn ich das jetzt I_MAP_LAST_BLOCK nenen würde hätte ich ein problem weil wir aktuelle 512 inodes erstellen

2018-10-15 18:32 UTC, closed without merging